/*
 * Copyright 2017 Abed Tony BenBrahim <tony.benrahim@10xdev.com>
 *     and Gwt-JElement project contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

 callback interface ObjectPropertyGetterFunction{
    any getValue();
 };

 callback interface ObjectPropertySetterFunction{
    void setValue(any value);
 };

dictionary ObjectPropertyDescriptor{
    required boolean configurable;
    required boolean enumerable;
    any value;
    boolean writable;
    ObjectPropertyGetterFunction get;
    ObjectPropertySetterFunction set;
};

[
    Constructor(optional object value),
    JsTypeName(Object),
    GenericType(T)
] interface JsObject {
    static JsObject assign(JsObject target, JsObject... sources);
    static JsObject create(JsObject proto, optional JsObject propertiesObject);
    [GenericReturn] JsObject defineProperties([GenericType(T)] JsObject obj, [GenericType(ObjectPropertyDescriptor)] JsObject properties);
    [GenericReturn] static JsObject defineProperty([GenericType(T)] JsObject obj, String propertyName, ObjectPropertyDescriptor descriptor);
    static sequence<sequence<any>> entries(JsObject obj);
    [GenericReturn] static JsObject freeze([GenericType(T)]JsObject obj);
    static ObjectPropertyDescriptor getOwnPropertyDescriptor(JsObject obj, String propertyName);
    [GenericType(ObjectPropertyDescriptor)] static JsObject getOwnPropertyDescriptors(JsObject obj);
    static sequence<String> getOwnPropertyNames(JsObject obj);
    static sequence<Object> getOwnPropertySymbols(JsObject obj);
    static JsObject getPrototypeOf(JsObject obj);
    static boolean is(Object value1, Object value2);
    static boolean isExtensible(JsObject obj);
    static boolean isFrozen(JsObject obj);
    static boolean isSealed(JsObject obj);
    static String[] keys(JsObject obj);
    static JsObject preventExtensions(JsObject obj);
    [GenericReturn] static JsObject seal([GenericType(T)] JsObject seal);
    static JsObject setPrototypeOf(JsObject obj, Object proto);
    [GenericType(T)] static sequence<any> values([GenericType(T)] JsObject obj);

    static attribute int length;
    static attribute JsObject prototype;

    String toJSON(); //serializer();
    String toString(); //stringifier;

    attribute JsObject __proto__;
    attribute Function constructor;

    void __defineGetter__(String propertyName, ObjectPropertyGetterFunction func);
    void __defineSetter__(String propertyName, ObjectPropertySetterFunction func);
    ObjectPropertyGetterFunction __lookupGetter__(String propertyName);
    ObjectPropertySetterFunction __lookupSetter__(String propertyName);
    boolean hasOwnProperty(String propertyName);
    boolean isPrototypeOf(JsObject obj);
    boolean propertyIsEnumerable(String propertyName);
    String toLocaleString();
    String toSource();
    any valueOf();

    //Function attributes and methods to break the cyclic inheritance


};

