/*
 * Copyright 2017 Abed Tony BenBrahim <tony.benrahim@10xdev.com>
 *     and Gwt-JElement project contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF object KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

//https://console.spec.whatwg.org/#console-interface

interface Console {
  // Logging
  void assert(optional boolean condition = false, object... data);
  void clear();
  void count(optional DOMString label = "default");
  void debug(object... data);
  void error(object... data);
  void info(object... data);
  void log(object... data);
  void table(object tabularData, optional sequence<DOMString> properties);
  void trace(object... data);
  void warn(object... data);
  void dir(object item, optional object? options);
  void dirxml(object... data);

  // Grouping
  void group(object... data);
  void groupCollapsed(object... data);
  void groupEnd();

  // Timing
  void time(optional DOMString label = "default");
  void timeEnd(optional DOMString label = "default");
};
