// Copyright 2015 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// https://url.spec.whatwg.org/#interface-urlsearchparams

typedef (sequence<sequence<USVString>> or record<USVString, USVString> or USVString) URLSearchParamsInit;

[
    Constructor(optional URLSearchParamsInit init = ""),
    Exposed=(Window,Worker),
    RaisesException=Constructor,
    GenericExtend(USVString)
] interface URLSearchParams {
    void append(USVString name, USVString value);
//    inherited
//    [ImplementedAs=deleteAllWithName] void delete(USVString name);
//    USVString? get(USVString name);
//    void set(USVString name, USVString value);
//    boolean has(USVString name);
//    stringifier;
    sequence<USVString> getAll(USVString name);

    void sort();

    iterable<USVString, USVString>;
};
